services:
    flight-data-analysis:
        ports:
            - 8888:8888
            - 8080:8080
        volumes:
            - ./data:/app/data
            - ./AdvancedData.ipynb:/app/AdvancedData.ipynb
        image: flight-data-analysis
